# Generated by Django 5.2.4 on 2025-08-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('residence_country', models.CharField(max_length=100)),
                ('origin_country', models.CharField(max_length=100)),
                ('age_group', models.CharField(choices=[('under_18', 'Under 18'), ('18_24', '18-24'), ('25_34', '25-34'), ('35_44', '35-44'), ('45_54', '45-54'), ('55_above', '55 and above')], max_length=20)),
                ('how_connected', models.CharField(max_length=100)),
                ('sourcing_from_home', models.BooleanField(default=False)),
                ('sourcing_from_home_freq', models.CharField(blank=True, max_length=100, null=True)),
                ('shoppingmethod', models.CharField(max_length=100)),
                ('shoppingmethod_description', models.TextField(blank=True, null=True)),
                ('shoppingchallenges', models.CharField(max_length=100)),
                ('shoppingchallenges_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
